services:
  - type: web
    name: Mensajero IVF
    env: static
    staticPublishPath: dist
    buildCommand: npm run build
     envVars:
      - key: VITE_API_URL
        value: https://mensajeroback.onrender.com/ 