services:
  - type: web
    name: mensajerofront
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist
    envVars:
      - key: VITE_API_URL
        value: https://mensajeroback.onrender.com